Feature/#3gguw2k/logout user
MatGoldwasser/BigChallenge pull request #4
Opened 2022-09-27 14:35 UTC by MatGoldwasser

2022-09-27 15:22 UTC, felipe-crosa commented on tests/Feature/LogoutUserTest.php
> +        $this->postJson('/api/logout', $user->toArray())->assertSuccessful();
no es necesario el $user->toArray()

2022-09-27 15:25 UTC, felipe-crosa commented on app/Transformers/UserTransformer.php
> +            'password' => $user->password
el front no deberia de tener la password

2022-09-27 15:34 UTC, felipe-crosa requested changes
Sacar la password del transformer

2022-09-27 15:44 UTC, merged

2022-09-27 17:12 UTC, sojeda commented on app/Transformers/UserTransformer.php
> +            'email' => $user->email
Por que sacamos el token de aca, no rompiste el login?

2022-09-28 19:29 UTC, MatGoldwasser commented on app/Http/Controllers/LogoutUser/LogoutUserController.php
> +class LogoutUserController extends Controller
ok

2022-09-28 19:37 UTC, sojeda commented on app/Transformers/UserTransformer.php
> +            'email' => $user->email
Esta perfecto enotnces